modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="the_everything_mod"
version="1.0.0"
displayName="The Everything Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Max, MCreator"

[[dependencies.the_everything_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"



